### ISSUE TITLE
difftastic not working

### ISSUE THREAD

**Issue by andyneff** [alexmurray/difftastic-snap#1]
I can't get `difftastic` to work (except in my home directory)

How does it work everywhere else?

## Setup

```
sudo snap install --edge difftastic
```

And I got this to work:

```
$ difftastic
USAGE:

    difft [OPTIONS] OLD-PATH NEW-PATH

For more information try --help
$ difftastic --version
Difftastic 0.24.0
```

But the command `difft` does not work.

## Problem

When I tried to run any two files, I always get the same result

```
$ difftastic before.py after.py
No such file: before.py
No such file: after.py
$ difftastic /src/before.py /src/after.py
No such file: /src/before.py
No such file: /src/after.py
```

## Workaround

I was able to discover, it works for files in my home dir

```
$ difftastic ~/before.py ~/after.py
...
```

## Other failed attempts

I tried `sudo snap install --classic --edge difftastic` but the `--classic` flag is ignored apparently:

```
Warning: flag --classic ignored for strictly confined snap difftastic
```

## OS Info

```
$ snap --version
snap    2.54.2-1.fc35
snapd   2.54.2-1.fc35
series  16
fedora  35
kernel  5.16.18-200.fc35.x86_64
```

**Comment by alexmurray** [comment]
[Snap confinement](https://snapcraft.io/docs/snap-confinement) means that the snap of difftastic can only see files in `$HOME` - to resolve this as you suggest the snap would have to be published with classic confinement however that comes with its own challenges (see Caveats at https://snapcraft.io/docs/reviewing-classic-confinement-snaps) - and an exception would have to be granted by the snapcraft.io store reviewers team to be allowed to publish the snap under classic confinement.

I can try and look into this if you feel it is a blocker for using the difftastic snap - let me know. The other option would be writing a wrapper in say your shell which copies files to say `$HOME/tmp` and then runs the real difftastic on those and deletes them afterwards? Or running it with say file-descriptors as arguments:

```
[amurray:/tmp] $ echo foo > a
[amurray:/tmp] $ echo bar > b
[amurray:/tmp] $ difftastic <(cat a) <(cat b)^C
[amurray:/tmp] 130 $ difftastic a b
No such file: a
No such file: b
[amurray:/tmp] 1 $ difftastic <(cat a) <(cat b)
/dev/fd/62 --- 1/2 --- Text
1 foo

/dev/fd/62 --- 2/2 --- Text
1 bar

```

**Comment by rooiratel** [comment]
Hi @andyneff  I this issue was closed this as completed, but I am still getting the same error/problem. How was this resolved?

When I run `sudo snap install --classic --edge difftastic`

I get this output 

`Warning: flag --classic ignored for strictly confined snap difftastic`

And if I try to run difftastic on anything outside my home directory I get the same `No such file` errors.

Please advise.

**Comment by alexmurray** [comment]
@rooiratel The difftastic snap is not currently published with classic confinement (and I am not sure I would necessarily be granted such an exception as per https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460) - so this is entirely expected unfortunately. Out of interest, how common is it for you to want to use the difftastic snap on files outside of your home directory? Also can you let me know some of the common paths for these files?

**Comment by rooiratel** [comment]
> Out of interest, how common is it for you to want to use the difftastic snap on files outside of your home directory?

The specific directory I am trying to use is : `~/IdeaProjects` 

However I am quite fond of using files in this directory via the "built in" Terminal in IntelliJ. So because of the way intelliJ works I am actually manipulating files in the /tmp/ directory. Which @andyneff  was also having problems with as mentioned above.

I use this every day for work. I don't have the time right now to fully migrate off of intellij to a fully neovim based setup. So I'll be stuck with this setup for a while. And I assume there are many others using Ubuntu + IntelliJ for similar purposes.

With this setup it is a pain to have a separate terminal window that you have to manually cd to the correct directory just to do some git stuff.


I have a strong dislike of snap, but I can't really help needing to use it at the moment. I used to use Arch Linux, which would have entirely avoided this whole problem. But because of entirely unrelated issues with my Corporate network and very specific issues with very specific versions of the Cisco VPN client, among other things, I was "forced" to switch to Ubuntu. I suspect many other people would also have some stupid reason they have to use Ubuntu instead of something with sane package management.
